# here we configure various aspects of Springboot application
# one of them is server

server:
  port : 3000  # here we are changing the port default 8080 to 3000

spring:
  main:
    web-application-type: servlet # web-application-type: none
                                  # this is how to turn off the web server && and default will be servlet
  #  if u want to del means u can do because default will servlet