# here we configure various aspects of Springboot application
# one of them is server
server:
  port: 8080
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5442/customer
    username: ezhil
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  main:
    web-application-type: servlet  # Default is servlet. To turn off the web server, use web-application-type: none
